#wakeUp heroku
name: 'dailyCloneWakeUp'

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: 53 1/7 * * *

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'WakeUp'
      run: |
        curl https://testhreroks.herokuapp.com/
